version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run build
      
      
  post_build:
    commands:
      - aws s3 cp s3://prasanna-aws-ecommerce s3://prasanna-aws-ecommerce --recursive --sse aws:kms

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: 'build'
